name: Docker Image CI

on: [push]

jobs:
  login:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/docker/login@master
      - name: Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag feltyrion:latest
      - name: Publish the Docker image
        run: docker push feltyrion:latest
