name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Login
        uses: actions/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        uses: actions/docker/cli@master
        with:
          args: build --tag jorisd/feltyrion:latest .
      - name: Publish the Docker image
        uses: actions/docker/cli@master
        with:
          args: push jorisd/feltyrion:latest
