name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Login
        uses: actions/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: "hub.docker.com"
      - name: Build the Docker image
        uses: actions/docker/cli@master
        with:
          args: build --tag feltyrion:latest .
      - name: Publish the Docker image
        uses: actions/docker/cli@master
        with:
          args: push jorisd/feltyrion:latest
